# Site settings
title: Тайтл
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: овнер
email: пошта
facebook_username: 
twitter_username:
github_username:
address:
  - line: лайн1
  - line: лайн2
  # Feel free to add more lines here 
telephone: +380991234567
copyright: Копірайт

# API settings
google_api_key: AIzaSyD9OEfuzdgiistCAij1-snTiensmauBv_E

# Build settings
markdown: kramdown